{{- if not .Values.ldap.existingSecret -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "another-ldap-auth.fullname" . }}
type: Opaque
data:
  LDAP_MANAGER_PASSWORD: PHlvdXItcGFzc3dvcmQtaW4tYmFzZTY0Pg==
{{- end }}