{{- if not .Values.ldap.existingSecret -}}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "another-ldap-auth.fullname" . }}
type: Opaque
data:
  LDAP_MANAGER_PASSWORD: <your-password-in-base64>
{{- end }}